package com.game.dao.impl;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.springframework.orm.hibernate3.support.HibernateDaoSupport;

import com.game.util.HibernateSessionFactory;



/**
 * Generated by ruandy.com Hibernate Tools. 
 * @author ruandy.com
 * 
 */
public class BaseHibernateDAO extends HibernateDaoSupport {
	

}
